#!/usr/bin/env bash

set -e

echo "Test hostname"
HOSTNAME=$(hostname)
test "$HOSTNAME" = "xiewq-macbook"

echo "Test brews"
test -x "$(which git)"
test -x "$(which nvim)"

echo "Test folders"
test -d ~/dev
test -d ~/work

echo "Test RCM symlinks"
test -s ~/.zshrc
test -s ~/.gitconfig
