#!/usr/bin/env bash

# 获取 brew 前缀路径
BREW_PREFIX="$(brew --prefix)"

export PATH="$BREW_PREFIX/opt/ruby/bin:$PATH"
export LDFLAGS="-L$BREW_PREFIX/opt/ruby/lib"
export CPPFLAGS="-I$BREW_PREFIX/opt/ruby/include"

gem install bundler
bundle config mirror.https://rubygems.org https://gems.ruby-china.com
