#!/usr/bin/env bash

test -x "$(which fnm)"

fnm completions --shell zsh > ~/.config/fnm/completions.zsh
fnm env --node-dist-mirror https://registry.npmmirror.com --use-on-cd --shell zsh > ~/.config/fnm/env.zsh

fnm install --lts --node-dist-mirror https://registry.npmmirror.com

test -x "$(which pnpm)"
pnpm --version

test -x "$(which node)"
node --version

test -x "$(which npm)"
npm --version

