#!/usr/bin/env bash

set -e

# 安装 vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# 检查 ~/.vimrc 是否存在
if [ ! -f ~/.vimrc ]; then
  echo "[WARN] ~/.vimrc 不存在，请先配置好 vim 插件相关内容后再运行本脚本。"
  exit 1
fi

# 实时输出插件安装过程
echo "[INFO] 开始自动安装 Vim 插件..."
vim -E -u ~/.vimrc +PlugInstall +qall

echo "[OK] Vim 插件已自动安装完毕。"
