#!/usr/bin/env bash

# 颜色定义
GREEN='\033[0;32m'
# RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}正在设置 Neovim${NC}"

# 检查 Lazy.nvim 是否已安装
LAZY_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/lazy/lazy.nvim"
if [ -d "$LAZY_PATH" ]; then
    echo -e "${YELLOW}Lazy.nvim 已安装，跳过插件安装${NC}"
else
    echo "安装 Neovim 插件..."
    # 运行 nvim 触发插件安装
    nvim --headless "+Lazy! sync" +qa
fi

echo "安装格式化工具和 linters..."
# 安装格式化工具和 linters（语言服务器由 mason-lspconfig 确保）
nvim --headless '+MasonInstall luacheck markdownlint revive stylua shfmt yamllint' +qa

echo -e "${GREEN}Neovim 设置完成${NC}"
