name: build
on: [push, pull_request]
if: "!contains(github.event.head_commit.message, '[ci skip]')"
jobs:
  ci:
    name: run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        run: bash ./bootstrap
      - name: CI
        run: bash ./test
