name: build
on: [push, pull_request]
jobs:
  ci:
    name: run
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true
    - name: build
      env:
        CI_MODE: true
      run: bash ./bootstrap
    - name: CI
      run: bash ./test
